### ISSUE TITLE
Implement fog of war

### ISSUE THREAD

**Issue by BodrickLight** [dndplayer/dnd-player#27]
Eventually it'd be nice to be calculated per-character, but at the very least some way of hiding areas of the map would be useful.

**Comment by chrisella** [comment]
Another possible option for this short term (suggested by Steven) is to put a new property on all objects which flags if it's visible to the DM only or not. 
This would allow the DM to hide tokens from players, but not the background. The background images etc could solve this temporarily by just importing a square black image which can be positioned around over the top of bits to hide them.

To improve the usability of the hiding for DM only, multi-select and multi-select property editing would be a huge boon.
