### ISSUE TITLE
Add ability to ping map

### ISSUE THREAD

**Issue by BodrickLight** [dndplayer/dnd-player#56]

**Comment by chrisella** [comment]
Started having a look at this.
Assuming we want to keep bits in Firebase it seems our options are:

- Use the Realtime Database which would work fairly easy as other clients would be able to easily detect the changing state and display pings. The downside of this is somehow we have to cleanup anything in the DB for this. Either the client that added the ping could remove it from the DB x secs later (but what if they disconnect, it will be orphaned) Or some function runs periodically to remove pings. This is assuming we want to remove them, we could just as well leave them in the DB (they won't use much space) and at-least in development it could be handy to know the historical state of pings etc.
- The Firebase messaging, which would work well for this also, BUT it seems actually sending a notification/message isn't trivial. Clients aren't supposed to be the initiators of this from what I have read in the docs, instead a server or function is suppose to trigger them.

**Comment by chrisella** [comment]
I've got most of this implemented (the way we discussed at lunch) and pushed so far in f98bc6270f50ad56f6c03133e2c682eedd79dc69 

I've got the remainder half finished - with the UI/Map showing actual pings almost done and a toggle button needed still to enable click to ping so it doesn't happen all the time (unless that's possibly desired).

**Comment by chrisella** [comment]
Now just need to finish the new animation and push that
