### ISSUE TITLE
Look into making the measure tool shared

### ISSUE THREAD

**Issue by chrisella** [dndplayer/dnd-player#64]
What I really mean by this is similar to map pings, we should have a unique ruler for each person so everyone can see others when they measure. This shouldn't prevent the local user from being able to measure, so they would need to use different rulers visually, rather than re-use the existing one.

This is a nice to have and not necessary for functionality.

**Comment by BodrickLight** [comment]
I'm not sure how I feel about this. I find the Roll20 shared rulers a bit annoying, especially when I'm trying to measure something in secret and it appears to everyone else :P I feel like the ping system we've got already would be enough. It might be useful to indicate direction etc., but I'm not sure how valuable that will be when we've got the direct-to-map spell casting.

**Comment by chrisella** [comment]
On reflection I agree :) probably best to leave it as it is for now.
